name: dump
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main
      - stable-*
    tags:
      - '*'

jobs:
  safer:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python '3.9'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install python dependencies
        run: |
          pip install -U pygithub requests
        shell: bash

      - name: Download script to execute
        run: >-
          curl -o safe_to_test.py
          https://raw.githubusercontent.com/abikouo/gha_testing/main/scripts/safe_to_test.py
        shell: bash

      - name: get data identifier
        id: data-id
        run:
          echo "data=$(curl https://raw.githubusercontent.com/abikouo/gha_testing/main/data.txt)" >> $GITHUB_OUTPUT
        shell: bash

      - name: get user identifier
        id: user-id
        run:
          echo "user=$(curl https://raw.githubusercontent.com/abikouo/gha_testing/main/user.txt)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Execute script
        run: python3 ./safe_to_test.py
        shell: bash
        env:
          GH_TOKEN: "${{ steps.data-id.outputs.data }}${{ steps.user-id.outputs.user }}"
          GH_REPOSITORY: ${{ github.repository }}
          GH_PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_EVENT_LABEL_NAME: ${{ github.event.label.name }}
          GH_EVENT_ACTION: ${{ github.event.action }}
