# Some tests require secrets from the repo
# and therefore require an approval/label to run
name: integration

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request_target:
    branches:
      - main
      - stable-*
    types:
      - labeled
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  safe-to-test:
    uses: abikouo/gha_testing/.github/workflows/safe-to-test.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}